#!/usr/bin/env bash

#source /platform/bash-exec

ENV_FILE="/etc/container_environment.sh"
ENV_DIR="/etc/container_environment/"
source $ENV_FILE
WORK_DIR=${LARAVEL_QUEUE_WORK_DIR:-"/app"}
ARTISAN="/usr/local/bin/php artisan"
DEFAULT_COMMAND="$ARTISAN queue:work"
QUEUE_WORK_COMMAND=${LARAVEL_QUEUE_WORK_COMMAND:-$DEFAULT_COMMAND}

set +e
for oneshot in `ls /platform/start-container.d/`
do
    echo "executing one shot start-up command /platform/start-container.d/$oneshot"
    /platform/start-container.d/$oneshot
done

cd $WORK_DIR
if [ -z "artisan" ]; then
    echo "No artisan found. stopping ..."
    exit 1
fi

exec chpst -e $ENV_DIR $LARAVEL_QUEUE_WORK_COMMAND
