#!/usr/bin/env bash

#source /platform/bash-exec

if [ ! -z "$WWWUID" ]; then
    usermod -u $WWWUID www-data;
    chown www-data /app;
    chown -R www-data /app/storage;
    chown -R www-data /app/bootstrap;
fi

if [ ! -z "$WWWGID" ]; then
    groupmod -g $WWWGID www-data
    chgrp www-data /app;
    chgrp -R www-data /app/storage;
    chgrp -R www-data /app/bootstrap;
fi

for oneshot in `ls /platform/start-container.d/`
do
    echo "executing one shot start-up command /platform/start-container.d/$oneshot"
    /platform/start-container.d/$oneshot
done

export SVDIR=/platform/services/
export SVWAIT=60

set -E
function shutdown () {
    # Disabling the traps to avoid a cascading
    trap - SIGINT SIGILL SIGABRT SIGFPE SIGSEGV SIGTERM SIGBUS SIGCHLD SIGKILL ERR

    echo "waiting for all services to exit ..."
    DONE=0
    SLEEP_COUNT=0
    SLEEP_MAX=$SVWAIT
    while [ $DONE -ne 1 ] && [ $SLEEP_COUNT -le $SLEEP_MAX ];
    do
        for x in `ls /platform/services/`;
        do
            echo "Stopping service /platform/services/$x ..."
            sv down $x
        done
        $(/usr/bin/sv status /platform/services/* | grep -q '^run:')
        DONE=$?
        echo "done is $DONE"
        if [ $DONE -eq 127 ]
        then
            exit 1
        fi
        SLEEP_COUNT+=1
        sleep 1
    done
    # terminate the runsv commands
    for x in `ls /platform/services/`;
    do
        echo "Stopping service /platform/services/$x ..."
        sv x $x
    done

    if [ $SLEEP_COUNT -le $SLEEP_MAX ]
    then
        exit 1
    fi

exit 0
}
trap shutdown SIGTERM SIGQUIT SIGINT;

function sigterm_cleanup_post () {
    shutdown
    return 0
}
function trap_exec_failure () {
    shutdown
    return 0
}

pids=()
for x in `ls /platform/services/`;
do
    echo "Staring service /platform/services/$x ..."
    exec /usr/bin/runsv  /platform/services/$x & pids+=($!)
done
for pid in ${pids[*]}; do
    wait $pids
done
