#!/usr/bin/env bash

#source /platform/bash-exec

ENV_FILE="/etc/container_environment.sh"
ENV_DIR="/etc/container_environment/"
source $ENV_FILE
COMMAND="/usr/local/bin/php artisan"
WORK_DIR=${LARAVEL_HORIZON_WORK_DIR:-"/app"}

set +e
for oneshot in `ls /platform/start-container.d/`
do
    echo "executing one shot start-up command /platform/start-container.d/$oneshot"
    /platform/start-container.d/$oneshot
done

$( $COMMAND | grep -q 'horizon:')
HAS_HORIZON=$?
echo "Artisan has horizon commands $HAS_HORIZON"
set -e

if [ "$HAS_HORIZON" -ne 0 ];
then
    echo "no horizon found under artisan  stopping ..."
    exit 1
fi

exec chpst -e $ENV_DIR $COMMAND horizon
