#!/usr/bin/env bash
set -ex

ENV_FILE="/etc/container_environment.sh"
ENV_DIR="/etc/container_environment/"
source $ENV_FILE
COMMAND="/usr/local/bin/php artisan horizon"
WORK_DIR=${LARAVEL_HORIZON_WORK_DIR:-"/app"}

cd $WORK_DIR
exec chpst -u www-data:www-data -e $ENV_DIR $COMMAND
