#!/usr/bin/env bash
set -ex

ENV_FILE="/etc/container_environment.sh"
ENV_DIR="/etc/container_environment/"
source $ENV_FILE
COMMAND="/usr/local/bin/php artisan"
WORK_DIR=${LARAVEL_HORIZON_WORK_DIR:-"/app"}

cd $WORK_DIR
if [ ! -f artisan ];
then
    echo "No artisan found under $WORK_DIR  stopping ..."
    sv down horizon
    exit 1
fi
$( $COMMAND | grep -q 'horizon:')
HAS_HORIZON=$?
echo "Artisan has horizon commands $HAS_HORIZON"
if [ "$HAS_HORIZON" -ne 0 ];
then
    echo "No horizon found under artisan  stopping ..."
    sv down horizon
    exit 1
fi

exec chpst -u www-data:www-data -e $ENV_DIR $COMMAND horizon
